// <auto-generated />
namespace ChipShip.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tookoutcloumnfromaddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tookoutcloumnfromaddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201709291348097_took out cloumn from address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
